In [20]:
# 矩阵乘法

import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print('A:\n', A)
print('B:\n', B)

print('A * B:\n', A * B)
print('A @ B:\n', A @ B)

A:
 [[3 4 9]
 [9 1 9]
 [8 5 1]]
B:
 [[4 8 3]
 [7 4 8]
 [8 5 9]]
A * B:
 [[12 32 27]
 [63  4 72]
 [64 25  9]]
A @ B:
 [[112  85 122]
 [115 121 116]
 [ 75  89  73]]


In [39]:
# 列表展开

print(*[1, 2, 3], 4)

print({1: 2, **{2: 3}})

print(*range(5), 2)

1 2 3 4
{1: 2, 2: 3}


(0, 1, 2, 3, 4, 2)

In [42]:
# 格式化字节

print(b'Hello %b!' % b'World')

print(b'x=%i y=%f' % (1, 2.5))

print(b'price: %a' % '10€')

b'Hello World!'
b'x=1 y=2.500000'
b"price: '10\\u20ac'"


In [44]:
# os.scandir

import os
de = os.scandir()

for entry in de:
    print(entry.name)
    print(entry.path)
    print(entry.is_file())

.ipynb_checkpoints
./.ipynb_checkpoints
False
async.ipynb
./async.ipynb
True
py35-new-syntax.ipynb
./py35-new-syntax.ipynb
True


In [1]:
# InterruptedError

from queue import Queue


q = Queue()
try:
    q.get(block=True)
except KeyboardInterrupt as err:
    print(dir(err))

['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'with_traceback']


In [24]:
import signal

def sig_hanlder(num, frame):
    print('get: ', num)
    
signal.signal(signal.SIGALRM, sig_hanlder)

signal.alarm(signal.SIGINT)

0

get:  14


In [8]:
signal.alarm(signal.SIGINT)

0

In [1]:
next(iter([]))

StopIteration: 

In [34]:
from __future__ import generator_stop

def gen():
    g = next(iter([]))
    yield g
    
    
next(gen())


RuntimeError: generator raised StopIteration

In [50]:
import math

# 10 和 1 的相对误差为 90%
math.isclose(10, 1, rel_tol=0.8)
# False
math.isclose(10, 1, rel_tol=0.9)
# True

# 2 和 3 的绝对误差为 1
math.isclose(2, 3, abs_tol=1)
# True
math.isclose(2, 3, abs_tol=0.9)
# False

False

In [7]:
class A:
    
    @property
    def val(self):
        """property docstring"""
        return 2
    
a = A()
print(A.val.__doc__)
A.val.__doc__ = 'new docstring'
print(A.val.__doc__)

property docstring
new docstring


In [14]:
import contextlib, io, logging


f = io.StringIO()
with contextlib.redirect_stderr(f):
    logging.error('stderr in context')
    
# ipython notebook 重定向了 strerr，所以这里看不到
# 你要到 python shell 里去执行
f.getvalue()
# 'ERROR:root:stderr in context\n'

AttributeError: 'RootLogger' object has no attribute 'set_handler'

In [19]:
from enum import Enum


Animal = Enum('Animal', 'cat dog maid', start=10)
Animal.cat

<Animal.cat: 10>

In [20]:
import heapq

a = ['9', '777', '55555']
b = ['88', '6666']

list(heapq.merge(a, b, key=len))
# ['9', '88', '777', '6666', '55555']
list(heapq.merge(reversed(a), reversed(b), key=len, reverse=True))
# ['55555', '6666', '777', '88', '9']

['55555', '6666', '777', '88', '9']

In [ ]:
from traceback import format_exc

In [30]:
import logging

try:
    1/0
except ZeroDivisionError as ex:
    logging.error('exception', exc_info=ex)